---
title: "Academic and Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Education

## University of California, Santa Barbara (09/2021 – 06/2024)
- Bachelor of Science, Data Science and Statistics
- Bachelor of Science, Applied Mathematics
- Overall GPA: 3.93/4.0; Major GPA: 3.97/4.0; Dean’s Honor

## Columbia University (09/2024 - 05/2026)
- Master of Science, Biostatistics (Theory and Method)

# Skills

- **Machine Learning**: Multiple Testing, Neural Network, NLP, LASSO, Random Forest, KNN
- **Statistics**: Stochastic Process, Nonparametric Method, ANOVA Analysis, Effects Models, Sign Tests, Mann-Whitney Tests, Chi-Squared Test, Bayesian Methods, Hypothesis test
- **Programming**: R, Python, C++, SAS, SQL
- **Mathematics**: Linear Algebra, Real Analysis, Number Analysis, Ordinary and Chaotic Differential Equation, Graph Theory
- **Economics**: Micro Economy, Macro Economy

# Experiences

## Part-time Biostatistician | Lifestyles-Sugentech | Wuhan, China (Remote) (09/2023 – 12/2023)
- Conducted clinical evaluation of a Human Chorionic Gonadotropin (HCG) test reagent for early pregnancy diagnosis.
- Compiled evaluation reports by analyzing over 600 urine samples using R.
- Engaged in data collection efforts to determine sample sizes and secure specialized data sources.

## Biostatistician | Wuhan Zhi Zhi Medicine | Wuhan, China (08/2023 – 09/2023)
- Developed R models to optimize sample sizes for CROs and pharmaceutical R&D.
- Analyzed data from medical records using SAS for further statistical analysis.

## Statistician | Humanwell Healthcare Group | Wuhan, China (Remote) (12/2022 – 01/2023)
- Coordinated projects with CROs in the development of generic drugs.
- Conducted statistical research for bioequivalence studies.

# Projects

## Data Science Capstone Project Cooperate with CALCOFI (09/2023 – 06/2024)
- Developed an interactive RShiny application to map and visualize eDNA and sighting data.
- Implemented noise reduction techniques on spectrogram data.
- It is posted in [github](https://github.com/PSTAT197-F23/Capstone-Scripps)

# Contact
- Email: [zhangpuyan4@gmail.com](mailto:zhangpuyan4@gmail.com)
- Phone: +1(805) 252-9988
- Address: 470 Main Street, Fort Lee, NJ